name: CD

on:
  # Run on pushes and pull-requests
  push:
  pull_request:

jobs:
  make_linux_gui_debug_build:
    name: Linux (${{ matrix.arch }}) GUI (debug)
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
        with:
          using-cmake: true
      - name: Make the build
        run: |
          make cmake-build
          mv build/cmake/debug/ballisticakit build/cmake/debug/staged
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: linux_${{ matrix.arch }}_gui_(debug)
          path: build/cmake/debug/staged

  make_linux_server_debug_build:
    name: Linux (${{ matrix.arch }}) Server (debug)
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
        with:
          using-cmake: true
      - name: Make the build
        run: make cmake-server-build
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: linux_${{ matrix.arch }}_server_(debug)
          path: build/cmake/server-debug/staged

  # Limiting mac prefab builds to arm only for now.
  # Leaving this here in case we re-enable them though.

  # make_mac_x86_64_gui_debug_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v6
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.13'
  #   - name: Setup project environment
  #     run: make env
  #   - name: Make the build
  #     run: make prefab-mac-x86-64-gui-debug-build
  #   - name: Upload the build
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: mac_x86_64_gui_(debug)
  #       path: build/prefab/full/mac_x86_64_gui

  # make_mac_x86_64_server_debug_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v6
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.13'
  #   - name: Setup project environment
  #     run: make env
  #   - name: Make the build
  #     run: make prefab-mac-x86-64-server-debug-build
  #   - name: Upload the build
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: mac_x86_64_server_(debug)
  #       path: build/prefab/full/mac_x86_64_server

  make_mac_arm64_gui_debug_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Make the build
        run: make prefab-mac-arm64-gui-debug-build
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: mac_arm64_gui_(debug)
          path: build/prefab/full/mac_arm64_gui

  make_mac_arm64_server_debug_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Make the build
        run: make prefab-mac-arm64-server-debug-build
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: mac_arm64_server_(debug)
          path: build/prefab/full/mac_arm64_server

  make_windows_x86_64_gui_debug_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Make the build
        run: make prefab-windows-x86-64-gui-debug-build
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: windows_x86_64_gui_(debug)
          path: build/prefab/full/windows_x86_64_gui

  make_windows_x86_64_server_debug_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Make the build
        run: make prefab-windows-x86-64-server-debug-build
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: windows_x86_64_server_(debug)
          path: build/prefab/full/windows_x86_64_server
