name: Nightly Build
on:
  # Run everyday at 5:30 UTC
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  make_docker_gui_debug_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make the build
        run: |
          make docker-gui-debug
          make docker-save
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: docker_gui(debug)
          path: build/docker/bombsquad_gui_debug_docker.tar
      - name: Push to github image repository
        run: |
          docker tag bombsquad_gui_debug:latest ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_gui:debug_nightly_x86_64
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_gui:debug_nightly_x86_64

  make_docker_server_debug_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make the build
        run: |
          make docker-server-debug
          make docker-save
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: docker_server(debug)
          path: build/docker/bombsquad_server_debug_docker.tar
      - name: Push to github image repository
        run: |
          docker tag bombsquad_server_debug:latest ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:debug_nightly_x86_64
          docker push ghcr.io/${GITHUB_REPOSITORY,,}/bombsquad_server:debug_nightly_x86_64

  make_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Make the build
        run: make docs
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: html_docs
          path: build/docs

  make_flatpak_gui_debug:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup build env
        uses: ./.github/actions/bombsquad_build_env
      - name: Cache Flatpak data
        id: cache-flatpak-sdk
        uses: actions/cache@v4
        env:
          cache-name: cache-flatpak
        with:
          path: |
            ~/.local/share/flatpak
            .cache/flatpak/flatpak-builder
            .cache/flatpak/build_dir
            .cache/flatpak/repo
          key: ${{ runner.os }}-${{runner.arch}}-${{ env.cache-name }}-${{ hashFiles('config/flatpak/net.froemling.BombSquad.yml') }}
          restore-keys: |
            ${{ runner.os }}-${{runner.arch}}-${{ env.cache-name }}-
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y flatpak flatpak-builder

      # This works but its nice to have precise control over the cache
      # - name: Build Flatpak
      #   uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      #   with:
      #     bundle: bombsquad.flatpak
      #     manifest-path: config/flatpak/net.froemling.BombSquad.yml
      #     cache-key: flatpak-builder-${{ hashFiles('config/flatpak/net.froemling.BombSquad.yml') }}-${{ github.sha }}

      - name: Make the build
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub org.freedesktop.Sdk//25.08
          sudo flatpak install -y flathub org.freedesktop.Platform//25.08
          sudo flatpak install -y flathub org.freedesktop.Sdk.Extension.llvm20//25.08
          make flatpak-linux
      - name: Upload the build
        uses: actions/upload-artifact@v4
        with:
          name: bombsquad_${{ matrix.arch }}(debug).flatpak
          path: build/flatpak/bombsquad.flatpak
